model Student {
  key: Long
  firstName: Text
  lastName: Text
  year: Int
  grades: List(Grade)
  mentor: Mentor
  repo: [
    findStudentByKey
  ]
}

model Grade {
  key: Long
  score: Double
  course: Course
}

model Course {
  key: Int
  courseName: String
  students: List(Student)
  repo: [
    findCourseByCourseName
  ]
}

model Mentor {
  key: Long
  firstName: Text
  lastName: Text
  repo: [
    findMentorByKey
  ]
}

model Teacher {
  key: Long
  firstName: Text
  lastName: Text
  courses: List(Course)
  repo: [
    findTeacherByKey
  ]
}